FROM nginx:1.19

LABEL maintainer="taiwan_temperature_app" \
  org.label-schema.name="web" \
  org.label-schema.vendor="taiwan_temperature_app" \
  org.label-schema.schema-version="1.0"

EXPOSE 3000

COPY build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]